export const studioViews = [
  {
    path: '/workbench',
    label: '工作台',
    group: 'core',
    lane: 'workflow',
    modes: ['development', 'delivery'],
    title: 'daduhe 主工作台',
    subtitle: '先看主链摘要，再进入 Launch / Monitor / Review / Release 四个固定工位',
    focus: ['主链摘要', '当前案例', '下一步工位'],
    actions: ['进入 Launch', '查看 Monitor', '打开 Review / Release'],
  },
  {
    path: '/projects',
    label: '项目壳',
    group: 'core',
    lane: 'support',
    modes: ['development', 'delivery'],
    title: '工程、案例与恢复点',
    subtitle: '作为 daduhe 主链的壳层中控，查看案例切换、历史运行与项目归属',
    focus: ['工程状态', '案例切换', '恢复点'],
    actions: ['选择工程', '刷新摘要', '打开最近会话'],
  },
  {
    path: '/analysis',
    label: '数据与资产',
    group: 'core',
    lane: 'support',
    modes: ['development', 'delivery'],
    title: '资料发现与资产视图',
    subtitle: '围绕数据来源、可信度、缺口与冲突展示资产状态',
    focus: ['来源清单', '可信度', '人工复核项'],
    actions: ['扫描资料', '筛选冲突', '进入资产详情'],
  },
  {
    path: '/modeling',
    label: '拓扑与 GIS',
    group: 'core',
    lane: 'support',
    modes: ['development', 'delivery'],
    title: '图形拓扑与 GIS 建模',
    subtitle: '统一承接拓扑画布、空间图层、控制断面候选与结果对比',
    focus: ['拓扑图元', 'GIS 图层', '空间校验'],
    actions: ['添加节点', '连接边', '启动 GIS 任务'],
  },
  {
    path: '/simulation',
    label: 'Launch',
    group: 'core',
    lane: 'workflow',
    modes: ['development', 'delivery'],
    title: 'Launch · 主链启动台',
    subtitle: '固定 daduhe pinned workflows、WorkflowRun 与执行策略，不再分散到多个入口',
    focus: ['pinned workflow', 'WorkflowRun', '启动策略'],
    actions: ['直接启动主链', '切换策略', '绑定日志'],
  },
  {
    path: '/review',
    label: 'Review / Release',
    group: 'core',
    lane: 'workflow',
    modes: ['development', 'delivery'],
    title: 'Review / Release · 审查交付台',
    subtitle: '固定 ReviewBundle、coverage、ReleaseManifest 与签发动作',
    focus: ['审查结论', '风险项', 'ReleaseManifest'],
    actions: ['查看审查', '核对 gate', '准备交付'],
  },
  {
    path: '/monitor',
    label: 'Monitor',
    group: 'core',
    lane: 'workflow',
    modes: ['development', 'delivery'],
    title: 'Monitor · 值守巡检台',
    subtitle: '围绕 live dashboard、日志尾部、checkpoint 与告警进行统一值守',
    focus: ['实时站点', '日志尾部', 'checkpoint'],
    actions: ['打开日志', '查看告警', '恢复任务'],
  },
  {
    path: '/extensions',
    label: '扩展中心',
    group: 'advanced',
    lane: 'developer',
    modes: ['development'],
    title: '统一扩展中心',
    subtitle: '管理 agent、skill、MCP、模型算法和 workflow 五类扩展',
    focus: ['扩展包', '版本兼容', '权限声明'],
    actions: ['启停扩展', '校验 schema', '打包发布'],
  },
  {
    path: '/ide',
    label: 'Terminal 模式',
    group: 'advanced',
    lane: 'developer',
    modes: ['development'],
    title: 'Terminal / Workspace 工作面',
    subtitle: '面向 ClaudeCode 内核的终端、文件树、Diff、搜索替换与开发宿主入口',
    focus: ['PTY 终端', '文件树', 'Diff'],
    actions: ['打开工作区', '切换终端', '执行命令'],
    surfaceMode: 'terminal',
  },
  {
    path: '/agent',
    label: 'Agent 模式',
    group: 'advanced',
    lane: 'developer',
    modes: ['development'],
    title: 'Agent 工作面',
    subtitle: '作为灵活 AI 调用入口，聚焦多轮对话、提示编排、证据解释与下一步建议',
    focus: ['多轮对话', '会话上下文', '证据解释'],
    actions: ['发起对话', '解释当前 case', '生成下一步动作'],
    surfaceMode: 'agent',
  },
  {
    path: '/notebook',
    label: 'Notebook 模式',
    group: 'advanced',
    lane: 'developer',
    modes: ['development'],
    title: 'Evidence Notebook 工作面',
    subtitle: '围绕 contracts、coverage、review bundle 与签发备注组织证据笔记',
    focus: ['证据卡片', '人工备注', '签发结论'],
    actions: ['插入证据', '记录结论', '准备签发'],
    surfaceMode: 'notebook',
  },
  {
    path: '/settings',
    label: '设置',
    group: 'system',
    modes: ['development', 'delivery'],
    title: '系统与个性化设置',
    subtitle: '配置桌面偏好、本地能力、主题和运行模式',
    focus: ['桌面设置', '本地能力', '同步策略'],
    actions: ['修改主题', '检查服务', '导出配置'],
  },
];

export const getStudioView = (path) =>
  studioViews.find((view) => path === view.path || path.startsWith(`${view.path}/`)) || studioViews[0];

export const getVisibleStudioViews = (mode) =>
  studioViews.filter((view) => !view.modes || view.modes.includes(mode));

export const developerSurfaces = [
  {
    key: 'terminal',
    label: 'Terminal',
    route: '/ide',
    summary: '直接连到 ClaudeCode / CLI 工作区与终端宿主',
  },
  {
    key: 'agent',
    label: 'Agent',
    route: '/agent',
    summary: '灵活 AI 调用、多轮对话、上下文解释与下一步建议',
  },
  {
    key: 'notebook',
    label: 'Notebook',
    route: '/notebook',
    summary: '围绕 evidence、review bundle、release gate 记录笔记与签发备注',
  },
];

export const getSurfaceByPath = (path) =>
  developerSurfaces.find((surface) => path === surface.route || path.startsWith(`${surface.route}/`)) || null;
